// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrDdfXKpdUFG-gOf_jheuImk3Ce4R-18E',
    appId: '1:278381638902:web:3faba22eda0987503ce8d7',
    messagingSenderId: '278381638902',
    projectId: 'tecappflutter',
    authDomain: 'tecappflutter.firebaseapp.com',
    storageBucket: 'tecappflutter.firebasestorage.app',
    measurementId: 'G-57QGEHJX7K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdZrsoiYN7hZj2cNE5C3WA4esjjPy5-Pw',
    appId: '1:278381638902:android:56d7a1d037b55aed3ce8d7',
    messagingSenderId: '278381638902',
    projectId: 'tecappflutter',
    storageBucket: 'tecappflutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUlkqqVafNp_NDkni5RK1x2-iWngDPZzg',
    appId: '1:278381638902:ios:2c489edae21926c13ce8d7',
    messagingSenderId: '278381638902',
    projectId: 'tecappflutter',
    storageBucket: 'tecappflutter.firebasestorage.app',
    iosBundleId: 'com.example.flutterAppFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUlkqqVafNp_NDkni5RK1x2-iWngDPZzg',
    appId: '1:278381638902:ios:2c489edae21926c13ce8d7',
    messagingSenderId: '278381638902',
    projectId: 'tecappflutter',
    storageBucket: 'tecappflutter.firebasestorage.app',
    iosBundleId: 'com.example.flutterAppFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrDdfXKpdUFG-gOf_jheuImk3Ce4R-18E',
    appId: '1:278381638902:web:e9664bec52ef44583ce8d7',
    messagingSenderId: '278381638902',
    projectId: 'tecappflutter',
    authDomain: 'tecappflutter.firebaseapp.com',
    storageBucket: 'tecappflutter.firebasestorage.app',
    measurementId: 'G-1755DQ4ETY',
  );
}
